name: Build and Release Debian Package

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          
      - name: Setup environment
        run: |
          # Add backports repository for Go 1.23.1
          echo "deb http://deb.debian.org/debian bookworm-backports main" > /etc/apt/sources.list.d/backports.list
          apt update
          
          # Install latest Go 1.23 from backports
          apt install -y -t bookworm-backports golang-1.23
          ln -s /usr/lib/go-1.23/bin/go /usr/local/bin/go
          
          # Install build tools
          apt install -y git-buildpackage devscripts
          
      - name: Change to repository directory
        run: cd fan2go-package
        
      - name: Import upstream source
        run: gbp import-orig --uscan --pristine-tar
        
      - name: Build package
        run: |
          gbp buildpackage \
            --git-upstream-branch=upstream \
            --git-debian-branch=debian \
            --git-export-dir=../build-area \
            -us -uc  # No signing
            
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ../build-area/*.*
          
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: artifacts
          
      - name: Get version information
        id: get_version
        run: |
          VERSION=$(dpkg-parsechangelog -l artifacts/*.dsc -S Version)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: fan2go ${{ steps.get_version.outputs.VERSION }} (Debian)
          body: |
            ### Debian Package for fan2go
            **Version**: ${{ steps.get_version.outputs.VERSION }}
            **Build Date**: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
            **Source Code**: [fan2go upstream](https://github.com/markusressel/fan2go)
            
            #### Installation
            ```bash
            sudo apt install ./fan2go_*_amd64.deb
            ```
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
