name: Build and Test

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create GitHub release after successful build'
        required: false
        default: false
        type: boolean
  push:
    branches: [debian/unstable]
    paths:
      - 'debian/**'
  workflow_call:
    inputs:
      create_release:
        description: 'Create GitHub release after successful build'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        distro: [bookworm, bullseye, trixie]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: debian/unstable
          fetch-depth: 0

      - name: Check upstream
        id: upstream
        run: |
          if ! uscan --report --dehs; then
            echo "New upstream version detected"
            echo "new_upstream=true" >> $GITHUB_OUTPUT
          else
            echo "No upstream changes found"
            echo "new_upstream=false" >> $GITHUB_OUTPUT
          fi


      - name: Build in container
        uses: addnab/docker-run-action@v3
        with:
          image: debian:trixie
          # Mount GitHub workspace (includes .git) to /workspace and set as working dir
          options: -v ${{ github.workspace }}:/workspace -w /workspace
          run: |
            apt-get update
            apt-get install -y devscripts git-buildpackage lintian golang-go
            apt-get build-dep -y .
            
            # Configure git for container environment
            # /workspace is the mount point we defined above in options
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git config --global --add safe.directory /workspace
            
            gbp buildpackage --git-export-dir=/build-area --git-ignore-new --git-upstream-branch=upstream --git-debian-branch=debian/unstable -us -uc
            
            echo "Outputs from the build are:"
            ls -la /build-area/* || exit 1
            
            echo "Running lintian on the built packages..."
            lintian /build-area/*.deb /build-area/*.dsc || true
            
            echo "===== MOVING ARTIFACTS TO WORKSPACE ====="
            echo "Current working directory:"
            pwd
            echo "Contents of /build-area:"
            ls -laR /build-area/ || echo "No /build-area directory"
            echo "Contents of /workspace:"
            ls -laR /workspace/ || echo "No /workspace directory"
            
            mkdir -p /workspace/artifacts
            mv /build-area/fan2go* /workspace/artifacts/
            echo "Artifacts moved to workspace:"
            ls -laR /workspace/artifacts/
            

      - name: Verify artifacts and extract version
        run: |
          echo "Current working directory on host:"
          pwd
          echo "Contents of current directory:"
          ls -la
          echo "Checking artifacts directory:"
          ls -la artifacts/ || echo "No artifacts directory"
          cp test-output.log artifacts/ || echo "No test-output.log"
          echo "Final artifacts:"
          ls -la artifacts/ || echo "Still no artifacts directory"
          
          echo "===== EXTRACTING VERSION ====="
          VERSION=$(ls artifacts/fan2go_*.deb | head -1 | sed 's/.*fan2go_\(.*\)_amd64\.deb/\1/')
          echo "Extracted version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create release
        if: |
          inputs.create_release == true ||
          steps.upstream.outputs.new_upstream == 'true'
        uses: softprops/action-gh-release@v1
        with:
          name: fan2go-${{ env.VERSION }}-${{ matrix.distro }}
          tag_name: fan2go-${{ env.VERSION }}-${{ matrix.distro }}
          body: |
            Debian ${{ matrix.distro }} build
            Source: ${{ github.sha }}
            
            This is an automated build from the debian/unstable branch.
            Lintian checks have been run - see attached logs for details.
          files: artifacts/*
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}