name: Build and Test

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create GitHub release after successful build'
        required: false
        default: false
        type: boolean
  push:
    branches: [debian/unstable]
    paths:
      - 'debian/**'
  workflow_call:
    inputs:
      create_release:
        description: 'Create GitHub release after successful build'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        distro: [bookworm, bullseye, trixie]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: debian/unstable
          fetch-depth: 0

      - name: Check upstream
        id: upstream
        run: |
          if ! uscan --report --dehs; then
            echo "New upstream version detected"
            echo "new_upstream=true" >> $GITHUB_OUTPUT
          else
            echo "No upstream changes found"
            echo "new_upstream=false" >> $GITHUB_OUTPUT
          fi


      - name: Build in container
        uses: addnab/docker-run-action@v3
        with:
          image: debian:trixie
          # Mount GitHub workspace (includes .git) to /workspace and set as working dir
          options: -v ${{ github.workspace }}:/workspace -w /workspace
          run: |
            apt-get update
            apt-get install -y devscripts git-buildpackage lintian golang-go
            apt-get build-dep -y .
            
            # Configure git for container environment
            # /workspace is the mount point we defined above in options
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git config --global --add safe.directory /workspace
            
            gbp buildpackage --git-export-dir=../build-area --git-ignore-new --git-upstream-branch=upstream --git-debian-branch=debian/unstable -us -uc
            
            echo "===== CHECKING BUILD OUTPUTS ====="
            ls -la ../build-area/fan2go* || exit 1
            
            echo "===== LINTIAN CHECKS ====="
            lintian ../build-area/*.deb ../build-area/*.dsc || true

      - name: Copy artifacts 
        run: |
          mkdir -p artifacts
          cp ../build-area/fan2go* artifacts/ 2>/dev/null || true
          cp test-output.log artifacts/ 2>/dev/null || true

      - name: Create release
        if: |
          inputs.create_release == true ||
          steps.upstream.outputs.new_upstream == 'true'
        uses: softprops/action-gh-release@v1
        with:
          name: fan2go-${{ matrix.distro }}-$(date +%Y%m%d)
          tag_name: build-${{ matrix.distro }}-${{ github.run_id }}
          body: |
            Debian ${{ matrix.distro }} build
            Source: ${{ github.sha }}
            
            This is an automated build from the debian/unstable branch.
            Lintian checks have been run - see attached logs for details.
          files: artifacts/*
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}